In [16]:
from tensorflow.keras.preprocessing.text import one_hot

In [17]:
### sentences
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good']

In [18]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [19]:
## Define the vocabulary size
voc_size = 10000    

In [20]:
### One Hot Represantation
one_hot_repr = [one_hot(words, voc_size) for words in sent]
one_hot_repr

[[6374, 4846, 8622, 5264],
 [6374, 4846, 8622, 4919],
 [6374, 2782, 8622, 1282],
 [5213, 8570, 1503, 4882, 5512],
 [5213, 8570, 1503, 4882, 3175],
 [5201, 6374, 3601, 8622, 3163],
 [2107, 7917, 54, 4882]]

In [21]:
## Word embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [22]:
import numpy as np

In [23]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding = 'pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6374 4846 8622 5264]
 [   0    0    0    0 6374 4846 8622 4919]
 [   0    0    0    0 6374 2782 8622 1282]
 [   0    0    0 5213 8570 1503 4882 5512]
 [   0    0    0 5213 8570 1503 4882 3175]
 [   0    0    0 5201 6374 3601 8622 3163]
 [   0    0    0    0 2107 7917   54 4882]]


In [24]:
## feature representation
dim = 10

In [31]:
model = Sequential()
model.add(Embedding(input_dim=voc_size, output_dim=dim, input_shape=(sent_length,))) 
model.compile(optimizer='adam', loss='mse')


c:\Users\erand\anaconda3\envs\study\Lib\site-packages\keras\src\layers\core\embedding.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [32]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [33]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step


array([[[-2.07922347e-02,  1.60073899e-02, -4.94105332e-02,
          3.24112438e-02, -4.64608558e-02, -4.53662053e-02,
          4.04174961e-02, -4.56141122e-02, -8.16391781e-03,
          7.00900704e-03],
        [-2.07922347e-02,  1.60073899e-02, -4.94105332e-02,
          3.24112438e-02, -4.64608558e-02, -4.53662053e-02,
          4.04174961e-02, -4.56141122e-02, -8.16391781e-03,
          7.00900704e-03],
        [-2.07922347e-02,  1.60073899e-02, -4.94105332e-02,
          3.24112438e-02, -4.64608558e-02, -4.53662053e-02,
          4.04174961e-02, -4.56141122e-02, -8.16391781e-03,
          7.00900704e-03],
        [-2.07922347e-02,  1.60073899e-02, -4.94105332e-02,
          3.24112438e-02, -4.64608558e-02, -4.53662053e-02,
          4.04174961e-02, -4.56141122e-02, -8.16391781e-03,
          7.00900704e-03],
        [ 2.46328376e-02,  6.18008524e-03,  4.58374508e-02,
          5.55764884e-04, -3.57901454e-02,  3.85543965e-02,
          3.17194574e-02, -1.14256032e-02,  1.047589

In [34]:
embedded_docs[0]

array([   0,    0,    0,    0, 6374, 4846, 8622, 5264])